### ISSUE TITLE
Handling points not on the network

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npw#42] opened 2024-12-11 15:28 UTC
Clearly this is known and in hand, just logging here to track it (apologies if this is spamming the issue tracker Dustin).

![image](https://github.com/user-attachments/assets/ecf2dee3-405f-47f6-a841-5e2fc3c9d663)

**Comment by dabreegster** [comment] 2024-12-15 12:36
Duplicate of #9

**Closed by dabreegster** 2024-12-15 12:36 UTC
